results_dir: "/work-zfs/abattle4/ashis/progres/spice_anlysis"
gene_annot: "/work-zfs/abattle4/ashis/progdata/scnet/gtex_v8_net/misc/gencode.v26.annotation.gene.txt"

# results_dir: "/Users/ashissaha/github/spice_analysis/results/spice_results"
# gene_annot: "/Users/ashissaha/github/annot/gencode.v26.annotation.gene.txt"

crossmap_threshold: 0
random_seed: 101

string:
  version: "11"
  species: 9606
  max_homology: 60

msigdb_species: "Homo sapiens"
pathways:
  hallmark: 
    cat: "H"
    subcat: ""
  kegg: 
    cat: "C2"
    subcat: "CP:KEGG"
  go: 
    cat: "C5"
    subcat: "BP"
  reactome: 
    cat: "C2"
    subcat: "CP:REACTOME"
  biocarta: 
    cat: "C2"
    subcat: "CP:BIOCARTA"

eval_opts:
  auc:
    curve: "FALSE"
    max: "TRUE"
    min: "TRUE"
    rand: "FALSE"
    dg: "FALSE"
  weight:
    na_handle: "known"
    na_rm: "FALSE"
    neg_handle: "error"
  precision:
    top: ["NA", 1000, 5000, 10000, 50000]
    threshold: [0.7, 0.4, 0.15]
  pathway_enrichment:
    min_gene: 5
    max_gene: 100
    iter: 10000
  trans_eqtl:
    top_edge: 10000
    max_cis_dist: 1000000
    max_crossmap_d: 1000000
    max_snp_per_run: 1000
  geodesic_rankdiff:
    d: [1, 2, 3, 4, 5]
    string_threshold: 0.7
    inweb_threshold: 0.7
    kegg_threshold: "0.00001"  # string to avoid auto-conversion to scientific notation

tissues: ['Adipose_Subcutaneous', 'Adipose_Visceral_Omentum', 'Adrenal_Gland',
          'Artery_Aorta', 'Artery_Coronary', 'Artery_Tibial',
          'Brain_Amygdala', 'Brain_Anterior_cingulate_cortex_BA24',
          'Brain_Caudate_basal_ganglia', 'Brain_Cerebellar_Hemisphere',
          'Brain_Cerebellum', 'Brain_Cortex', 'Brain_Frontal_Cortex_BA9',
          'Brain_Hippocampus', 'Brain_Hypothalamus',
          'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia',
          'Brain_Spinal_cord_cervical_c-1', 'Brain_Substantia_nigra',
          'Breast_Mammary_Tissue',
          'Cells_Cultured_fibroblasts', 'Cells_EBV-transformed_lymphocytes',
          'Colon_Sigmoid', 'Colon_Transverse',
          'Esophagus_Gastroesophageal_Junction', 'Esophagus_Mucosa', 'Esophagus_Muscularis',
          'Heart_Atrial_Appendage', 'Heart_Left_Ventricle',
          'Kidney_Cortex', 'Liver', 'Lung',
          'Minor_Salivary_Gland', 'Muscle_Skeletal', 'Nerve_Tibial',
          'Ovary', 'Pancreas', 'Pituitary', 'Prostate',
          'Skin_Not_Sun_Exposed_Suprapubic', 'Skin_Sun_Exposed_Lower_leg',
          'Small_Intestine_Terminal_Ileum', 'Spleen', 'Stomach',
          'Testis', 'Thyroid', 'Uterus', 'Vagina', 'Whole_Blood']

correction_labels: ["corrected"]
n_genes: [500, 1500, 5000]
gene_selection: ["AXPVAR"]
methods: ["wgcna", "spice"]

validation_tissues: ['Brain_Cerebellum', "Pancreas", "Heart_Left_Ventricle", "Lung"]
validation_correction_labels: ["corrected"]
validation_n_genes: [1500]
validation_gene_selection: ["AXPVAR"]
validation_methods: [ 'wgcna_pearson_unsigned_0.6', 'wgcna_pearson_unsigned_0.7', 'wgcna_pearson_unsigned_0.8', 'wgcna_pearson_unsigned_0.9', 
                      'wgcna_pearson_signed_0.6', 'wgcna_pearson_signed_0.7', 'wgcna_pearson_signed_0.8', 'wgcna_pearson_signed_0.9',
                      'wgcna_spearman_unsigned_0.6', 'wgcna_spearman_unsigned_0.7', 'wgcna_spearman_unsigned_0.8', 'wgcna_spearman_unsigned_0.9', 
                      'wgcna_spearman_signed_0.6', 'wgcna_spearman_signed_0.7', 'wgcna_spearman_signed_0.8', 'wgcna_spearman_signed_0.9',
                      
                      'pearson', 'spearman', 
                      'genie3', 'et_genie3',
                      
                      'aracne_spearman_e0_freq', 'aracne_spearman_e.05_freq', 'aracne_spearman_e.1_freq',
                      'aracne_spearman_e0_width', 'aracne_spearman_e.05_width', 'aracne_spearman_e.1_width',
                      
                      'aracne_pearson_e0_freq', 'aracne_pearson_e.05_freq', 'aracne_pearson_e.1_freq',
                      'aracne_pearson_e0_width', 'aracne_pearson_e.05_width', 'aracne_pearson_e.1_width',
                      
                      'aracne_empirical_e0_freq', 'aracne_empirical_e.05_freq', 'aracne_empirical_e.1_freq',
                      'aracne_empirical_e0_width', 'aracne_empirical_e.05_width', 'aracne_empirical_e.1_width',
                      
                      'mrnetb_spearman_freq', 'mrnetb_pearson_freq', 'mrnetb_empirical_freq',
                      'mrnetb_spearman_width', 'mrnetb_pearson_width', 'mrnetb_empirical_width',
                      
                      'mrnet_spearman_freq', 'mrnet_pearson_freq', 'mrnet_empirical_freq',
                      'mrnet_spearman_width', 'mrnet_pearson_width', 'mrnet_empirical_width',
                      
                      'clr_spearman_freq', 'clr_pearson_freq', 'clr_empirical_freq', 
                      'clr_spearman_width', 'clr_pearson_width', 'clr_empirical_width', 
                      
                      'glasso_likelihood', 
                      'glasso_5k', 'glasso_10k', 'glasso_25k', 'glasso_50k',
                      
                      'pcorr_pearson', 'pcorr_spearman', 
                        
                      'random',
                        
                      'spice_Mp_G1_Ra_A0', 'spice_Mp_G1_Rm_A0', 'spice_Mp_G1_RM_A0', 'spice_Mp_G1_Ra_A1', 'spice_Mp_G1_Rm_A1', 'spice_Mp_G1_RM_A1',
                      'spice_Mp_G.9_Ra_A0', 'spice_Mp_G.9_Rm_A0', 'spice_Mp_G.9_RM_A0', 'spice_Mp_G.9_Ra_A1', 'spice_Mp_G.9_Rm_A1', 'spice_Mp_G.9_RM_A1',
                      'spice_Mp_G.8_Ra_A0', 'spice_Mp_G.8_Rm_A0', 'spice_Mp_G.8_RM_A0', 'spice_Mp_G.8_Ra_A1', 'spice_Mp_G.8_Rm_A1', 'spice_Mp_G.8_RM_A1',
                      'spice_Mp_G.7_Ra_A0', 'spice_Mp_G.7_Rm_A0', 'spice_Mp_G.7_RM_A0', 'spice_Mp_G.7_Ra_A1', 'spice_Mp_G.7_Rm_A1', 'spice_Mp_G.7_RM_A1',
                      
                      'spice_Ms_G1_Ra_A0', 'spice_Ms_G1_Rm_A0', 'spice_Ms_G1_RM_A0', 'spice_Ms_G1_Ra_A1', 'spice_Ms_G1_Rm_A1', 'spice_Ms_G1_RM_A1',
                      'spice_Ms_G.9_Ra_A0', 'spice_Ms_G.9_Rm_A0', 'spice_Ms_G.9_RM_A0', 'spice_Ms_G.9_Ra_A1', 'spice_Ms_G.9_Rm_A1', 'spice_Ms_G.9_RM_A1',
                      'spice_Ms_G.8_Ra_A0', 'spice_Ms_G.8_Rm_A0', 'spice_Ms_G.8_RM_A0', 'spice_Ms_G.8_Ra_A1', 'spice_Ms_G.8_Rm_A1', 'spice_Ms_G.8_RM_A1',
                      'spice_Ms_G.7_Ra_A0', 'spice_Ms_G.7_Rm_A0', 'spice_Ms_G.7_RM_A0', 'spice_Ms_G.7_Ra_A1', 'spice_Ms_G.7_Rm_A1', 'spice_Ms_G.7_RM_A1',
                      
                      # 'spice_ME_G1_Ra_A0', 'spice_ME_G1_Rm_A0', 'spice_ME_G1_RM_A0', 'spice_ME_G1_Ra_A1', 'spice_ME_G1_Rm_A1', 'spice_ME_G1_RM_A1',
                      # 'spice_ME_G.9_Ra_A0', 'spice_ME_G.9_Rm_A0', 'spice_ME_G.9_RM_A0', 'spice_ME_G.9_Ra_A1', 'spice_ME_G.9_Rm_A1', 'spice_ME_G.9_RM_A1',
                      # 'spice_ME_G.8_Ra_A0', 'spice_ME_G.8_Rm_A0', 'spice_ME_G.8_RM_A0', 'spice_ME_G.8_Ra_A1', 'spice_ME_G.8_Rm_A1', 'spice_ME_G.8_RM_A1',
                      # 'spice_ME_G.7_Ra_A0', 'spice_ME_G.7_Rm_A0', 'spice_ME_G.7_RM_A0', 'spice_ME_G.7_Ra_A1', 'spice_ME_G.7_Rm_A1', 'spice_ME_G.7_RM_A1',
                      
                      'spice_MP_G1_Ra_A0', 'spice_MP_G1_Rm_A0', 'spice_MP_G1_RM_A0', 'spice_MP_G1_Ra_A1', 'spice_MP_G1_Rm_A1', 'spice_MP_G1_RM_A1',
                      'spice_MP_G.9_Ra_A0', 'spice_MP_G.9_Rm_A0', 'spice_MP_G.9_RM_A0', 'spice_MP_G.9_Ra_A1', 'spice_MP_G.9_Rm_A1', 'spice_MP_G.9_RM_A1',
                      'spice_MP_G.8_Ra_A0', 'spice_MP_G.8_Rm_A0', 'spice_MP_G.8_RM_A0', 'spice_MP_G.8_Ra_A1', 'spice_MP_G.8_Rm_A1', 'spice_MP_G.8_RM_A1',
                      'spice_MP_G.7_Ra_A0', 'spice_MP_G.7_Rm_A0', 'spice_MP_G.7_RM_A0', 'spice_MP_G.7_Ra_A1', 'spice_MP_G.7_Rm_A1', 'spice_MP_G.7_RM_A1']


test_tissues: ['Adipose_Subcutaneous', 'Adipose_Visceral_Omentum', 'Adrenal_Gland',
              'Artery_Aorta', 'Artery_Coronary', 'Artery_Tibial',
              'Brain_Amygdala', 'Brain_Anterior_cingulate_cortex_BA24',
              'Brain_Caudate_basal_ganglia', 'Brain_Cerebellar_Hemisphere',
              'Brain_Cerebellum', 'Brain_Cortex', 'Brain_Frontal_Cortex_BA9',
              'Brain_Hippocampus', 'Brain_Hypothalamus',
              'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia',
              'Brain_Spinal_cord_cervical_c-1', 'Brain_Substantia_nigra',
              'Breast_Mammary_Tissue',
              'Cells_Cultured_fibroblasts', 'Cells_EBV-transformed_lymphocytes',
              'Colon_Sigmoid', 'Colon_Transverse',
              'Esophagus_Gastroesophageal_Junction', 'Esophagus_Mucosa', 'Esophagus_Muscularis',
              'Heart_Atrial_Appendage', 'Heart_Left_Ventricle',
              'Kidney_Cortex', 'Liver', 'Lung',
              'Minor_Salivary_Gland', 'Muscle_Skeletal', 'Nerve_Tibial',
              'Ovary', 'Pancreas', 'Pituitary', 'Prostate',
              'Skin_Not_Sun_Exposed_Suprapubic', 'Skin_Sun_Exposed_Lower_leg',
              'Small_Intestine_Terminal_Ileum', 'Spleen', 'Stomach',
              'Testis', 'Thyroid', 'Uterus', 'Vagina', 'Whole_Blood']

test_correction_labels: ["corrected"]
test_n_genes: [5000]
test_gene_selection: ["AXPVAR"]
test_methods: ["et_genie3", "spice", "wgcna", "mrnetb", "aracne", "glasso_10k", "pcorr", "random", "mrnet", "pearson", "spearman", "clr", "glasso_likelihood", "glasso_5k", "spice_Mp_G.8_Ra_A1_I200", "spice_Mp_G1_Ra_A1", "spice_c" ]

### for debugging
# test_tissues: ['Brain_Cerebellum', "Lung"]
# test_methods: ["et_genie3", "spice", "wgcna"]

chipseq_tissue_map:
  Brain_Amygdala: "Brain"
  Brain_Anterior_cingulate_cortex_BA24: "Brain"
  Brain_Caudate_basal_ganglia: "Brain"
  Brain_Cerebellar_Hemisphere: "Brain"
  Brain_Cerebellum: "Brain"
  Brain_Cortex: "Brain"
  Brain_Frontal_Cortex_BA9: "Brain"
  Brain_Hippocampus: "Brain"
  Brain_Hypothalamus: "Brain"
  Brain_Nucleus_accumbens_basal_ganglia: "Brain"
  Brain_Putamen_basal_ganglia: "Brain"
  Brain_Spinal_cord_cervical_c-1: "Brain"
  Brain_Substantia_nigra: "Brain"
  Breast_Mammary_Tissue: "Breast"
  Cells_EBV-transformed_lymphocytes: "Lymphocytes_Cells_EBV-transformed_lymphocytes"
  Colon_Sigmoid: "Colon"
  Colon_Transverse: "Colon"
  Kidney_Cortex: "Kidney"
  Liver: "Liver"
  Lung: "Lung"
  Uterus: "Uterus_Epithelial"
  Whole_Blood: "Blood"
  Adipose_Subcutaneous: ""
  Adipose_Visceral_Omentum: ""
  Adrenal_Gland: ""
  Artery_Aorta:  ""
  Artery_Coronary:  ""
  Artery_Tibial: ""
  Cells_Cultured_fibroblasts: ""
  Esophagus_Gastroesophageal_Junction: ""
  Esophagus_Mucosa: ""
  Esophagus_Muscularis: ""
  Heart_Atrial_Appendage: ""
  Heart_Left_Ventricle: ""
  Minor_Salivary_Gland: ""
  Muscle_Skeletal: ""
  Nerve_Tibial: ""
  Ovary: ""
  Pancreas: ""
  Pituitary: ""
  Prostate: ""
  Skin_Not_Sun_Exposed_Suprapubic: ""
  Skin_Sun_Exposed_Lower_leg: ""
  Small_Intestine_Terminal_Ileum: ""
  Spleen: ""
  Stomach: ""
  Testis: ""
  Thyroid: ""
  Vagina: ""

genotype:
  prefix: "/work-zfs/abattle4/lab_data/GTEx_v8_trans_eqtl_data_processed_by_brian/processed_genotypes/GTEx_Analysis_2017-06-05_v9_WholeGenomeSeq_838Indiv_"
  suffix: "_dosage_MAF_05_not_in_repeat.RData"
  chromosomes: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 
                'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12',
                'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 
                'chr19', 'chr20', 'chr21', 'chr22', 'chrX']
