__default__:
  partition: shared
  nodes: 1
  ntasks: 1
  time: 30  # min
  output: "{wildcards.results_dir}/logs/{rule}/slurm-%j.out"
  error: "{wildcards.results_dir}/logs/{rule}/slurm-%j.out"
  job-name: "{rule}"

run_gtex_network:
  time: "{params.runtime}"
  ntasks: "{params.thread}"
  