__default__:
  partition: shared
  nodes: 1
  ntasks: 1
  time: 30  # min
  output: "{wildcards.results_dir}/logs/{rule}/slurm-%j.out"
  error: "{wildcards.results_dir}/logs/{rule}/slurm-%j.out"
  job-name: "{rule}"

run_gtex_network:
  time: "{params.runtime}"
  ntasks: "{params.thread}"
  job-name: "{wildcards.method}"

run_string_ppi_auc:
  ntasks: "{params.thread}"
  
run_string_ppi_hub_auc:
  ntasks: "{params.thread}"
  
run_string_ppi_spearman_cor:
  ntasks: "{params.thread}"
  
run_string_ppi_precision:
  ntasks: "{params.thread}"
  
eval_string_kegg_ppi_auc:
  ntasks: "{params.thread}"
  
eval_string_kegg_ppi_hub_auc:
  ntasks: "{params.thread}"
  
eval_string_kegg_ppi_spearman_cor:
  ntasks: "{params.thread}"
  
eval_string_kegg_ppi_precision:
  ntasks: "{params.thread}"

eval_kegg_interaction_auc:
  ntasks: "{params.thread}"
  
eval_kegg_interaction_hub_auc:
  ntasks: "{params.thread}"
  
eval_kegg_interaction_spearman_cor:
  ntasks: "{params.thread}"
  
eval_kegg_interaction_precision:
  ntasks: "{params.thread}"

eval_chipseq_interaction_auc:
  ntasks: "{params.thread}"

eval_chipseq_interaction_hub_auc:
  ntasks: "{params.thread}"

eval_chipseq_interaction_spearman_cor:
  ntasks: "{params.thread}"

eval_chipseq_interaction_precision:
  ntasks: "{params.thread}"

eval_string_exp_ppi_auc:
  ntasks: "{params.thread}"
  
eval_string_exp_ppi_hub_auc:
  ntasks: "{params.thread}"
  
eval_string_exp_ppi_spearman_cor:
  ntasks: "{params.thread}"
  
eval_string_exp_ppi_precision:
  ntasks: "{params.thread}"

eval_inweb_ppi_auc:
  ntasks: "{params.thread}"
  
eval_inweb_ppi_hub_auc:
  ntasks: "{params.thread}"
  
eval_inweb_ppi_spearman_cor:
  ntasks: "{params.thread}"
  
eval_inweb_ppi_precision:
  ntasks: "{params.thread}"
  
eval_shared_pathway:
  ntasks: "{params.thread}"

eval_pathway_enrichment:
  ntasks: "{params.thread}"

get_string_ppi:
  ntasks: "{params.thread}"

get_string_kegg_ppi:
  ntasks: "{params.thread}"

get_inweb_ppi:
  ntasks: "{params.thread}"

process_snps_nearby_genes_for_trans_eqtl:
  ntasks: "{params.thread}"

eval_trans_eqtl_n_egenes:
  time: "{params.runtime}"
  ntasks: "{params.thread}"
